const countryCurrencyData = [
    { countryName: "Afghanistan", currency: "Afghan afghani", currencyCode: "AFN" },
    { countryName: "Albania", currency: "Albanian lek", currencyCode: "ALL" },
    { countryName: "Algeria", currency: "Algerian dinar", currencyCode: "DZD" },
    { countryName: "Andorra", currency: "Euro", currencyCode: "EUR" },
    { countryName: "Angola", currency: "Angolan kwanza", currencyCode: "AOA" },
    { countryName: "Antigua and Barbuda", currency: "East Caribbean dollar", currencyCode: "XCD" },
    { countryName: "Argentina", currency: "Argentine peso", currencyCode: "ARS" },
    { countryName: "Armenia", currency: "Armenian dram", currencyCode: "AMD" },
    { countryName: "Australia", currency: "Australian dollar", currencyCode: "AUD" },
    { countryName: "Austria", currency: "Euro", currencyCode: "EUR" },
    { countryName: "Azerbaijan", currency: "Azerbaijani manat", currencyCode: "AZN" },
    { countryName: "Bahamas", currency: "Bahamian dollar", currencyCode: "BSD" },
    { countryName: "Bahrain", currency: "Bahraini dinar", currencyCode: "BHD" },
    { countryName: "Bangladesh", currency: "Bangladeshi taka", currencyCode: "BDT" },
    { countryName: "Barbados", currency: "Barbadian dollar", currencyCode: "BBD" },
    { countryName: "Belarus", currency: "Belarusian ruble", currencyCode: "BYN" },
    { countryName: "Belgium", currency: "Euro", currencyCode: "EUR" },
    { countryName: "Belize", currency: "Belize dollar", currencyCode: "BZD" },
    { countryName: "Benin", currency: "West African CFA franc", currencyCode: "CFA" },
    { countryName: "Bhutan", currency: "Bhutanese ngultrum", currencyCode: "BTN" },
    { countryName: "Bolivia", currency: "Bolivian boliviano", currencyCode: "BOB" },
    { countryName: "Bosnia and Herzegovina", currency: "Bosnia and Herzegovina convertible mark", currencyCode: "BAM" },
    { countryName: "Botswana", currency: "Botswana pula", currencyCode: "BWP" },
    { countryName: "Brazil", currency: "Brazilian real", currencyCode: "BRL" },
    { countryName: "Brunei", currency: "Brunei dollar", currencyCode: "BND" },
    { countryName: "Bulgaria", currency: "Bulgarian lev", currencyCode: "BGN" },
    { countryName: "Burkina Faso", currency: "West African CFA franc", currencyCode: "CFA" },
    { countryName: "Burundi", currency: "Burundian franc", currencyCode: "BIF" },
    { countryName: "Cabo Verde", currency: "Cape Verdean escudo", currencyCode: "CVE" },
    { countryName: "Cambodia", currency: "Cambodian riel", currencyCode: "KHR" },
    { countryName: "Cameroon", currency: "Central African CFA franc", currencyCode: "CFA" },
    { countryName: "Canada", currency: "Canadian dollar", currencyCode: "CAD" },
    { countryName: "Central African Republic", currency: "Central African CFA franc", currencyCode: "CFA" },
    { countryName: "Chad", currency: "Central African CFA franc", currencyCode: "CFA" },
    { countryName: "Chile", currency: "Chilean peso", currencyCode: "CLP" },
    { countryName: "China", currency: "Chinese yuan", currencyCode: "CNY" },
    { countryName: "Colombia", currency: "Colombian peso", currencyCode: "COP" },
    { countryName: "Comoros", currency: "Comorian franc", currencyCode: "KMF" },
    { countryName: "Congo, Democratic Republic of the", currency: "Congolese franc", currencyCode: "CDF" },
    { countryName: "Congo, Republic of the", currency: "Central African CFA franc", currencyCode: "CFA" },
    { countryName: "Costa Rica", currency: "Costa Rican colón", currencyCode: "CRC" },
    { countryName: "Croatia", currency: "Croatian kuna", currencyCode: "HRK" },
    { countryName: "Cuba", currency: "Cuban peso", currencyCode: "CUP" },
    { countryName: "Cyprus", currency: "Euro", currencyCode: "EUR" },
    { countryName: "Czech Republic", currency: "Czech koruna", currencyCode: "CZK" },
    { countryName: "Denmark", currency: "Danish krone", currencyCode: "DKK" },
    { countryName: "Djibouti", currency: "Djiboutian franc", currencyCode: "DJF" },
    { countryName: "Dominica", currency: "East Caribbean dollar", currencyCode: "XCD" },
    { countryName: "Dominican Republic", currency: "Dominican peso", currencyCode: "DOP" },
    { countryName: "Ecuador", currency: "United States dollar", currencyCode: "USD" },
    { countryName: "Egypt", currency: "Egyptian pound", currencyCode: "EGP" },
    { countryName: "El Salvador", currency: "United States dollar", currencyCode: "USD" },
    { countryName: "Equatorial Guinea", currency: "Central African CFA franc", currencyCode: "CFA" },
    { countryName: "Eritrea", currency: "Eritrean nakfa", currencyCode: "ERN" },
    { countryName: "Estonia", currency: "Euro", currencyCode: "EUR" },
    { countryName: "Eswatini", currency: "Swazi lilangeni", currencyCode: "SZL" },
    { countryName: "Ethiopia", currency: "Ethiopian birr", currencyCode: "ETB" },
    { countryName: "Fiji", currency: "Fijian dollar", currencyCode: "FJD" },
    { countryName: "Finland", currency: "Euro", currencyCode: "EUR" },
    { countryName: "France", currency: "Euro", currencyCode: "EUR" },
    { countryName: "Gabon", currency: "Central African CFA franc", currencyCode: "CFA" },
    { countryName: "Gambia", currency: "Gambian dalasi", currencyCode: "GMD" },
    { countryName: "Georgia", currency: "Georgian lari", currencyCode: "GEL" },
    { countryName: "Germany", currency: "Euro", currencyCode: "EUR" },
    { countryName: "Ghana", currency: "Ghanaian cedi", currencyCode: "GHS" },
    { countryName: "Greece", currency: "Euro", currencyCode: "EUR" },
    { countryName: "Grenada", currency: "East Caribbean dollar", currencyCode: "XCD" },
    { countryName: "Guatemala", currency: "Guatemalan quetzal", currencyCode: "GTQ" },
    { countryName: "Guinea", currency: "Guinean franc", currencyCode: "GNF" },
    { countryName: "Guinea-Bissau", currency: "West African CFA franc", currencyCode: "CFA" },
    { countryName: "Guyana", currency: "Guyanese dollar", currencyCode: "GYD" },
    { countryName: "Haiti", currency: "Haitian gourde", currencyCode: "HTG" },
    { countryName: "Honduras", currency: "Honduran lempira", currencyCode: "HNL" },
    { countryName: "Hungary", currency: "Hungarian forint", currencyCode: "HUF" },
    { countryName: "Iceland", currency: "Icelandic króna", currencyCode: "ISK" },
    { countryName: "India", currency: "Indian rupee", currencyCode: "INR" },
    { countryName: "Indonesia", currency: "Indonesian rupiah", currencyCode: "IDR" },
    { countryName: "Iran", currency: "Iranian rial", currencyCode: "IRR" },
    { countryName: "Iraq", currency: "Iraqi dinar", currencyCode: "IQD" },
    { countryName: "Ireland", currency: "Euro", currencyCode: "EUR" },
    { countryName: "Israel", currency: "Israeli new shekel", currencyCode: "ILS" },
    { countryName: "Italy", currency: "Euro", currencyCode: "EUR" },
    { countryName: "Jamaica", currency: "Jamaican dollar", currencyCode: "JMD" },
    { countryName: "Japan", currency: "Japanese yen", currencyCode: "JPY" },
    { countryName: "Jordan", currency: "Jordanian dinar", currencyCode: "JOD" },
    { countryName: "Kazakhstan", currency: "Kazakhstani tenge", currencyCode: "KZT" },
    { countryName: "Kenya", currency: "Kenyan shilling", currencyCode: "KES" },
    { countryName: "Kiribati", currency: "Australian dollar", currencyCode: "AUD" },
    { countryName: "Korea, North", currency: "North Korean won", currencyCode: "KPW" },
    { countryName: "Korea, South", currency: "South Korean won", currencyCode: "KRW" },
    { countryName: "Kuwait", currency: "Kuwaiti dinar", currencyCode: "KWD" },
    { countryName: "Kyrgyzstan", currency: "Kyrgyzstani som", currencyCode: "KGS" },
    { countryName: "Laos", currency: "Laotian kip", currencyCode: "LAK" },
    { countryName: "Latvia", currency: "Euro", currencyCode: "EUR" },
    { countryName: "Lebanon", currency: "Lebanese pound", currencyCode: "LBP" },
    { countryName: "Lesotho", currency: "Lesotho loti", currencyCode: "LSL" },
    { countryName: "Liberia", currency: "Liberian dollar", currencyCode: "LRD" },
    { countryName: "Libya", currency: "Libyan dinar", currencyCode: "LYD" },
    { countryName: "Liechtenstein", currency: "Swiss franc", currencyCode: "CHF" },
    { countryName: "Lithuania", currency: "Euro", currencyCode: "EUR" },
    { countryName: "Luxembourg", currency: "Euro", currencyCode: "EUR" },
    { countryName: "Madagascar", currency: "Malagasy ariary", currencyCode: "MGA" },
    { countryName: "Malawi", currency: "Malawian kwacha", currencyCode: "MWK" },
    { countryName: "Malaysia", currency: "Malaysian ringgit", currencyCode: "MYR" },
    { countryName: "Maldives", currency: "Maldivian rufiyaa", currencyCode: "MVR" },
    { countryName: "Mali", currency: "West African CFA franc", currencyCode: "CFA" },
    { countryName: "Malta", currency: "Euro", currencyCode: "EUR" },
    { countryName: "Marshall Islands", currency: "United States dollar", currencyCode: "USD" },
    { countryName: "Mauritania", currency: "Mauritanian ouguiya", currencyCode: "MRU" },
    { countryName: "Mauritius", currency: "Mauritian rupee", currencyCode: "MUR" },
    { countryName: "Mexico", currency: "Mexican peso", currencyCode: "MXN" },
    { countryName: "Micronesia", currency: "United States dollar", currencyCode: "USD" },
    { countryName: "Moldova", currency: "Moldovan leu", currencyCode: "MDL" },
    { countryName: "Monaco", currency: "Euro", currencyCode: "EUR" },
    { countryName: "Mongolia", currency: "Mongolian tugrik", currencyCode: "MNT" },
    { countryName: "Montenegro", currency: "Euro", currencyCode: "EUR" },
    { countryName: "Morocco", currency: "Moroccan dirham", currencyCode: "MAD" },
    { countryName: "Mozambique", currency: "Mozambican metical", currencyCode: "MZN" },
    { countryName: "Myanmar", currency: "Burmese kyat", currencyCode: "MMK" },
    { countryName: "Namibia", currency: "Namibian dollar", currencyCode: "NAD" },
    { countryName: "Nauru", currency: "Australian dollar", currencyCode: "AUD" },
    { countryName: "Nepal", currency: "Nepalese rupee", currencyCode: "NPR" },
    { countryName: "Netherlands", currency: "Euro", currencyCode: "EUR" },
    { countryName: "New Zealand", currency: "New Zealand dollar", currencyCode: "NZD" },
    { countryName: "Nicaragua", currency: "Nicaraguan córdoba", currencyCode: "NIO" },
    { countryName: "Niger", currency: "West African CFA franc", currencyCode: "CFA" },
    { countryName: "Nigeria", currency: "Nigerian naira", currencyCode: "NGN" },
    { countryName: "North Macedonia", currency: "Macedonian denar", currencyCode: "MKD" },
    { countryName: "Norway", currency: "Norwegian krone", currencyCode: "NOK" },
    { countryName: "Oman", currency: "Omani rial", currencyCode: "OMR" },
    { countryName: "Pakistan", currency: "Pakistani rupee", currencyCode: "PKR" },
    { countryName: "Palau", currency: "United States dollar", currencyCode: "USD" },
    { countryName: "Panama", currency: "Balboa", currencyCode: "PAB" },
    { countryName: "Papua New Guinea", currency: "Kina", currencyCode: "PGK" },
    { countryName: "Paraguay", currency: "Paraguayan guarani", currencyCode: "PYG" },
    { countryName: "Peru", currency: "Sol", currencyCode: "PEN" },
    { countryName: "Philippines", currency: "Philippine peso", currencyCode: "PHP" },
    { countryName: "Poland", currency: "Polish złoty", currencyCode: "PLN" },
    { countryName: "Portugal", currency: "Euro", currencyCode: "EUR" },
    { countryName: "Qatar", currency: "Qatari riyal", currencyCode: "QAR" },
    { countryName: "Romania", currency: "Romanian leu", currencyCode: "RON" },
    { countryName: "Russia", currency: "Russian ruble", currencyCode: "RUB" },
    { countryName: "Rwanda", currency: "Rwandan franc", currencyCode: "RWF" },
    { countryName: "Saint Kitts and Nevis", currency: "East Caribbean dollar", currencyCode: "XCD" },
    { countryName: "Saint Lucia", currency: "East Caribbean dollar", currencyCode: "XCD" },
    { countryName: "Saint Vincent and the Grenadines", currency: "East Caribbean dollar", currencyCode: "XCD" },
    { countryName: "Samoa", currency: "Samoan tala", currencyCode: "WST" },
    { countryName: "San Marino", currency: "Euro", currencyCode: "EUR" },
    { countryName: "Sao Tome and Principe", currency: "São Tomé and Príncipe dobra", currencyCode: "STN" },
    { countryName: "Saudi Arabia", currency: "Saudi riyal", currencyCode: "SAR" },
    { countryName: "Senegal", currency: "West African CFA franc", currencyCode: "CFA" },
    { countryName: "Serbia", currency: "Serbian dinar", currencyCode: "RSD" },
    { countryName: "Seychelles", currency: "Seychellois rupee", currencyCode: "SCR" },
    { countryName: "Sierra Leone", currency: "Sierra Leonean leone", currencyCode: "SLL" },
    { countryName: "Singapore", currency: "Singapore dollar", currencyCode: "SGD" },
    { countryName: "Slovakia", currency: "Euro", currencyCode: "EUR" },
    { countryName: "Slovenia", currency: "Euro", currencyCode: "EUR" },
    { countryName: "Solomon Islands", currency: "Solomon Islands dollar", currencyCode: "SBD" },
    { countryName: "Somalia", currency: "Somali shilling", currencyCode: "SOS" },
    { countryName: "South Africa", currency: "South African rand", currencyCode: "ZAR" },
    { countryName: "South Sudan", currency: "South Sudanese pound", currencyCode: "SSP" },
    { countryName: "Spain", currency: "Euro", currencyCode: "EUR" },
    { countryName: "Sri Lanka", currency: "Sri Lankan rupee", currencyCode: "LKR" },
    { countryName: "Sudan", currency: "Sudanese pound", currencyCode: "SDG" },
    { countryName: "Suriname", currency: "Surinamese dollar", currencyCode: "SRD" },
    { countryName: "Sweden", currency: "Swedish krona", currencyCode: "SEK" },
    { countryName: "Switzerland", currency: "Swiss franc", currencyCode: "CHF" },
    { countryName: "Syria", currency: "Syrian pound", currencyCode: "SYP" },
    { countryName: "Taiwan", currency: "New Taiwan dollar", currencyCode: "TWD" },
    { countryName: "Tajikistan", currency: "Tajikistani somoni", currencyCode: "TJS" },
    { countryName: "Tanzania", currency: "Tanzanian shilling", currencyCode: "TZS" },
    { countryName: "Thailand", currency: "Thai baht", currencyCode: "THB" },
    { countryName: "Timor-Leste", currency: "United States dollar", currencyCode: "USD" },
    { countryName: "Togo", currency: "West African CFA franc", currencyCode: "CFA" },
    { countryName: "Tonga", currency: "Paʻanga", currencyCode: "TOP" },
    { countryName: "Trinidad and Tobago", currency: "Trinidad and Tobago dollar", currencyCode: "TTD" },
    { countryName: "Tunisia", currency: "Tunisian dinar", currencyCode: "TND" },
    { countryName: "Turkey", currency: "Turkish lira", currencyCode: "TRY" },
    { countryName: "Turkmenistan", currency: "Turkmen manat", currencyCode: "TMT" },
    { countryName: "Tuvalu", currency: "Australian dollar", currencyCode: "AUD" },
    { countryName: "Uganda", currency: "Ugandan shilling", currencyCode: "UGX" },
    { countryName: "Ukraine", currency: "Ukrainian hryvnia", currencyCode: "UAH" },
    { countryName: "United Arab Emirates", currency: "United Arab Emirates dirham", currencyCode: "AED" },
    { countryName: "United Kingdom", currency: "Pound sterling", currencyCode: "GBP" },
    { countryName: "United States", currency: "United States dollar", currencyCode: "USD" },
    { countryName: "Uruguay", currency: "Uruguayan peso", currencyCode: "UYU" },
    { countryName: "Uzbekistan", currency: "Uzbekistani som", currencyCode: "UZS" },
    { countryName: "Vanuatu", currency: "Vanuatu vatu", currencyCode: "VUV" },
    { countryName: "Vatican City", currency: "Euro", currencyCode: "EUR" },
    { countryName: "Venezuela", currency: "Venezuelan bolívar", currencyCode: "VES" },
    { countryName: "Vietnam", currency: "Vietnamese đồng", currencyCode: "VND" },
    { countryName: "Yemen", currency: "Yemeni rial", currencyCode: "YER" },
    { countryName: "Zambia", currency: "Zambian kwacha", currencyCode: "ZMK" },
    { countryName: "Zimbabwe", currency: "Zimbabwean dollar", currencyCode: "ZWD" }
];

export {countryCurrencyData}